/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage.exploring;

/**
 *
 * @author Darae
 */
public class HideMap extends javax.swing.JPanel {

    /**
     * Creates new form HideMap
     */
    public HideMap() {
        initComponents();
    }
    public void setNoti(String s) {
    	notification1.setM(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathPanel = new javax.swing.JPanel();
        nowPos = new javax.swing.JLabel();
        nextPos = new javax.swing.JLabel();
        notiPanel = new javax.swing.JPanel();
        notification1 = new guipackage.component.Notification();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.BorderLayout());

        nowPos.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        nowPos.setText("from ");

        nextPos.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        nextPos.setText("to ");

        javax.swing.GroupLayout pathPanelLayout = new javax.swing.GroupLayout(pathPanel);
        pathPanel.setLayout(pathPanelLayout);
        pathPanelLayout.setHorizontalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nowPos)
                    .addComponent(nextPos))
                .addContainerGap(919, Short.MAX_VALUE))
        );
        pathPanelLayout.setVerticalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(nowPos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextPos)
                .addGap(18, 18, 18))
        );

        add(pathPanel, java.awt.BorderLayout.PAGE_START);

        notiPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        notiPanel.setRequestFocusEnabled(false);
        notiPanel.setLayout(new javax.swing.OverlayLayout(notiPanel));
        notiPanel.add(notification1);

        add(notiPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nextPos;
    private javax.swing.JPanel notiPanel;
    private guipackage.component.Notification notification1;
    private javax.swing.JLabel nowPos;
    private javax.swing.JPanel pathPanel;
    // End of variables declaration//GEN-END:variables
}
