/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage.settings;

import java.awt.CardLayout;

/**
 *
 * @author Darae
 */
public class SettingsCard extends javax.swing.JPanel {
    CardLayout layout = new CardLayout();
    public SetBlobs blobPanel;
    public SetPos posPanel;
    /**
     * Creates new form SettingsCard
     */
    public SettingsCard(int r, int c) {
        initComponents();
        blobPanel = new SetBlobs(r,c);
        posPanel = new SetPos(r,c);
        createCard();
    }
    
    private void createCard(){
        setLayout(layout);
        add(blobPanel,"blob");
        add(posPanel, "pos");
        layout.show(this, "blob");
    }
    
    public void changeCard(String s){ //1?���? pos
            layout.show(this, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
